site_name: Spatial Data of Municipalities (Maps)
copyright: "Spatial Data of Municipalities (Maps)  is licensed under the <a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International (CC BY 4.0)</a>"
pages:
    - Home: index.md
    - Contributing: contributing.md
    - Reference: reference.md
    - Municipalities:
        - Ahmedabad: ahmedabad.md
        - Bangalore: bangalore.md
        - Bhopal: bhopal.md
        - Pune: pune.md
        - Bhubaneswar: bhubaneswar.md 
    - Maps:
      - 'Assembly Constituencies': 'assembly-constituencies.md'
      - 'Parliamentary constituencies': 'parliamentary-constituencies.md'
      - 'States': 'states.md'
      - 'Districts': 'districts.md'
      - 'Spatial data of Municipalities': 'index.md'
      - 'India Village Boundaries(Maps)': 'indian_village_boundaries.md'
site_dir: './../docs'
extra_css:
    - css/extra.css
theme:
    name: null
    custom_dir: 'cinder'